/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MemoryAnchor {
  export type SessionAnchorStruct = {
    sessionHash: BytesLike;
    timestamp: BigNumberish;
    anchoredBy: AddressLike;
  };

  export type SessionAnchorStructOutput = [
    sessionHash: string,
    timestamp: bigint,
    anchoredBy: string
  ] & { sessionHash: string; timestamp: bigint; anchoredBy: string };
}

export interface MemoryAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_SESSIONS_PER_AGENT"
      | "anchorSession"
      | "getSessionCount"
      | "getSessionHistory"
      | "getSessionHistoryPaginated"
      | "isOperator"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "setOperator"
      | "transferOwnership"
      | "unpause"
      | "verifySession"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "SessionAnchored"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_SESSIONS_PER_AGENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anchorSession",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionHistoryPaginated",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySession",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_SESSIONS_PER_AGENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionHistoryPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySession",
    data: BytesLike
  ): Result;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, authorised: boolean];
  export type OutputTuple = [operator: string, authorised: boolean];
  export interface OutputObject {
    operator: string;
    authorised: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionAnchoredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    sessionHash: BytesLike,
    anchoredBy: AddressLike,
    timestamp: BigNumberish,
    sessionIndex: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    sessionHash: string,
    anchoredBy: string,
    timestamp: bigint,
    sessionIndex: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    sessionHash: string;
    anchoredBy: string;
    timestamp: bigint;
    sessionIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemoryAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): MemoryAnchor;
  waitForDeployment(): Promise<this>;

  interface: MemoryAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_SESSIONS_PER_AGENT: TypedContractMethod<[], [bigint], "view">;

  anchorSession: TypedContractMethod<
    [tokenId: BigNumberish, sessionHash: BytesLike, userAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getSessionCount: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getSessionHistory: TypedContractMethod<
    [tokenId: BigNumberish],
    [MemoryAnchor.SessionAnchorStructOutput[]],
    "view"
  >;

  getSessionHistoryPaginated: TypedContractMethod<
    [tokenId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [MemoryAnchor.SessionAnchorStructOutput[]],
    "view"
  >;

  isOperator: TypedContractMethod<[operator: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [operator: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifySession: TypedContractMethod<
    [tokenId: BigNumberish, sessionHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_SESSIONS_PER_AGENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "anchorSession"
  ): TypedContractMethod<
    [tokenId: BigNumberish, sessionHash: BytesLike, userAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSessionCount"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSessionHistory"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [MemoryAnchor.SessionAnchorStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSessionHistoryPaginated"
  ): TypedContractMethod<
    [tokenId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [MemoryAnchor.SessionAnchorStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOperator"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySession"
  ): TypedContractMethod<
    [tokenId: BigNumberish, sessionHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SessionAnchored"
  ): TypedContractEvent<
    SessionAnchoredEvent.InputTuple,
    SessionAnchoredEvent.OutputTuple,
    SessionAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SessionAnchored(uint256,bytes32,address,uint256,uint256)": TypedContractEvent<
      SessionAnchoredEvent.InputTuple,
      SessionAnchoredEvent.OutputTuple,
      SessionAnchoredEvent.OutputObject
    >;
    SessionAnchored: TypedContractEvent<
      SessionAnchoredEvent.InputTuple,
      SessionAnchoredEvent.OutputTuple,
      SessionAnchoredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
